;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $83,$78,$84,$00,$85,$05,$01,$84,$9d,$01,$84,$4d,$85,$06,$01,$84
	.byte $ad,$00
