.define strip_1_pointers \
        strip_1_ace_hearts, \
        strip_1_two_hearts, \
        strip_1_three_hearts, \
        strip_1_four_hearts, \
        strip_1_five_hearts, \
        strip_1_six_hearts, \
        strip_1_seven_hearts, \
        strip_1_eight_hearts, \
        strip_1_nine_hearts, \
        strip_1_ten_hearts, \
        strip_1_jack_hearts, \
        strip_1_queen_hearts, \
        strip_1_king_hearts, \
        strip_1_ace_diamonds, \
        strip_1_two_diamonds, \
        strip_1_three_diamonds, \
        strip_1_four_diamonds, \
        strip_1_five_diamonds, \
        strip_1_six_diamonds, \
        strip_1_seven_diamonds, \
        strip_1_eight_diamonds, \
        strip_1_nine_diamonds, \
        strip_1_ten_diamonds, \
        strip_1_jack_diamonds, \
        strip_1_queen_diamonds, \
        strip_1_king_diamonds, \
        strip_1_ace_spades, \
        strip_1_two_spades, \
        strip_1_three_spades, \
        strip_1_four_spades, \
        strip_1_five_spades, \
        strip_1_six_spades, \
        strip_1_seven_spades, \
        strip_1_eight_spades, \
        strip_1_nine_spades, \
        strip_1_ten_spades, \
        strip_1_jack_spades, \
        strip_1_queen_spades, \
        strip_1_king_spades, \
        strip_1_ace_clubs, \
        strip_1_two_clubs, \
        strip_1_three_clubs, \
        strip_1_four_clubs, \
        strip_1_five_clubs, \
        strip_1_six_clubs, \
        strip_1_seven_clubs, \
        strip_1_eight_clubs, \
        strip_1_nine_clubs, \
        strip_1_ten_clubs, \
        strip_1_jack_clubs, \
        strip_1_queen_clubs, \
        strip_1_king_clubs, \
        strip_1_joker
strip_1_pointers_l: .lobytes strip_1_pointers
strip_1_pointers_h: .hibytes strip_1_pointers
.define strip_2_pointers \
        strip_2_ace_hearts, \
        strip_2_two_hearts, \
        strip_2_three_hearts, \
        strip_2_four_hearts, \
        strip_2_five_hearts, \
        strip_2_six_hearts, \
        strip_2_seven_hearts, \
        strip_2_eight_hearts, \
        strip_2_nine_hearts, \
        strip_2_ten_hearts, \
        strip_2_jack_hearts, \
        strip_2_queen_hearts, \
        strip_2_king_hearts, \
        strip_2_ace_diamonds, \
        strip_2_two_diamonds, \
        strip_2_three_diamonds, \
        strip_2_four_diamonds, \
        strip_2_five_diamonds, \
        strip_2_six_diamonds, \
        strip_2_seven_diamonds, \
        strip_2_eight_diamonds, \
        strip_2_nine_diamonds, \
        strip_2_ten_diamonds, \
        strip_2_jack_diamonds, \
        strip_2_queen_diamonds, \
        strip_2_king_diamonds, \
        strip_2_ace_spades, \
        strip_2_two_spades, \
        strip_2_three_spades, \
        strip_2_four_spades, \
        strip_2_five_spades, \
        strip_2_six_spades, \
        strip_2_seven_spades, \
        strip_2_eight_spades, \
        strip_2_nine_spades, \
        strip_2_ten_spades, \
        strip_2_jack_spades, \
        strip_2_queen_spades, \
        strip_2_king_spades, \
        strip_2_ace_clubs, \
        strip_2_two_clubs, \
        strip_2_three_clubs, \
        strip_2_four_clubs, \
        strip_2_five_clubs, \
        strip_2_six_clubs, \
        strip_2_seven_clubs, \
        strip_2_eight_clubs, \
        strip_2_nine_clubs, \
        strip_2_ten_clubs, \
        strip_2_jack_clubs, \
        strip_2_queen_clubs, \
        strip_2_king_clubs, \
        strip_2_joker
strip_2_pointers_l: .lobytes strip_2_pointers
strip_2_pointers_h: .hibytes strip_2_pointers
.define strip_3_pointers \
        strip_3_ace_hearts, \
        strip_3_two_hearts, \
        strip_3_three_hearts, \
        strip_3_four_hearts, \
        strip_3_five_hearts, \
        strip_3_six_hearts, \
        strip_3_seven_hearts, \
        strip_3_eight_hearts, \
        strip_3_nine_hearts, \
        strip_3_ten_hearts, \
        strip_3_jack_hearts, \
        strip_3_queen_hearts, \
        strip_3_king_hearts, \
        strip_3_ace_diamonds, \
        strip_3_two_diamonds, \
        strip_3_three_diamonds, \
        strip_3_four_diamonds, \
        strip_3_five_diamonds, \
        strip_3_six_diamonds, \
        strip_3_seven_diamonds, \
        strip_3_eight_diamonds, \
        strip_3_nine_diamonds, \
        strip_3_ten_diamonds, \
        strip_3_jack_diamonds, \
        strip_3_queen_diamonds, \
        strip_3_king_diamonds, \
        strip_3_ace_spades, \
        strip_3_two_spades, \
        strip_3_three_spades, \
        strip_3_four_spades, \
        strip_3_five_spades, \
        strip_3_six_spades, \
        strip_3_seven_spades, \
        strip_3_eight_spades, \
        strip_3_nine_spades, \
        strip_3_ten_spades, \
        strip_3_jack_spades, \
        strip_3_queen_spades, \
        strip_3_king_spades, \
        strip_3_ace_clubs, \
        strip_3_two_clubs, \
        strip_3_three_clubs, \
        strip_3_four_clubs, \
        strip_3_five_clubs, \
        strip_3_six_clubs, \
        strip_3_seven_clubs, \
        strip_3_eight_clubs, \
        strip_3_nine_clubs, \
        strip_3_ten_clubs, \
        strip_3_jack_clubs, \
        strip_3_queen_clubs, \
        strip_3_king_clubs, \
        strip_3_joker
strip_3_pointers_l: .lobytes strip_3_pointers
strip_3_pointers_h: .hibytes strip_3_pointers
.define strip_4_pointers \
        strip_4_ace_hearts, \
        strip_4_two_hearts, \
        strip_4_three_hearts, \
        strip_4_four_hearts, \
        strip_4_five_hearts, \
        strip_4_six_hearts, \
        strip_4_seven_hearts, \
        strip_4_eight_hearts, \
        strip_4_nine_hearts, \
        strip_4_ten_hearts, \
        strip_4_jack_hearts, \
        strip_4_queen_hearts, \
        strip_4_king_hearts, \
        strip_4_ace_diamonds, \
        strip_4_two_diamonds, \
        strip_4_three_diamonds, \
        strip_4_four_diamonds, \
        strip_4_five_diamonds, \
        strip_4_six_diamonds, \
        strip_4_seven_diamonds, \
        strip_4_eight_diamonds, \
        strip_4_nine_diamonds, \
        strip_4_ten_diamonds, \
        strip_4_jack_diamonds, \
        strip_4_queen_diamonds, \
        strip_4_king_diamonds, \
        strip_4_ace_spades, \
        strip_4_two_spades, \
        strip_4_three_spades, \
        strip_4_four_spades, \
        strip_4_five_spades, \
        strip_4_six_spades, \
        strip_4_seven_spades, \
        strip_4_eight_spades, \
        strip_4_nine_spades, \
        strip_4_ten_spades, \
        strip_4_jack_spades, \
        strip_4_queen_spades, \
        strip_4_king_spades, \
        strip_4_ace_clubs, \
        strip_4_two_clubs, \
        strip_4_three_clubs, \
        strip_4_four_clubs, \
        strip_4_five_clubs, \
        strip_4_six_clubs, \
        strip_4_seven_clubs, \
        strip_4_eight_clubs, \
        strip_4_nine_clubs, \
        strip_4_ten_clubs, \
        strip_4_jack_clubs, \
        strip_4_queen_clubs, \
        strip_4_king_clubs, \
        strip_4_joker
strip_4_pointers_l: .lobytes strip_4_pointers
strip_4_pointers_h: .hibytes strip_4_pointers
.define strip_1b_pointers \
        strip_1b_ace_hearts, \
        strip_1b_two_hearts, \
        strip_1b_three_hearts, \
        strip_1b_four_hearts, \
        strip_1b_five_hearts, \
        strip_1b_six_hearts, \
        strip_1b_seven_hearts, \
        strip_1b_eight_hearts, \
        strip_1b_nine_hearts, \
        strip_1b_ten_hearts, \
        strip_1b_jack_hearts, \
        strip_1b_queen_hearts, \
        strip_1b_king_hearts, \
        strip_1b_ace_diamonds, \
        strip_1b_two_diamonds, \
        strip_1b_three_diamonds, \
        strip_1b_four_diamonds, \
        strip_1b_five_diamonds, \
        strip_1b_six_diamonds, \
        strip_1b_seven_diamonds, \
        strip_1b_eight_diamonds, \
        strip_1b_nine_diamonds, \
        strip_1b_ten_diamonds, \
        strip_1b_jack_diamonds, \
        strip_1b_queen_diamonds, \
        strip_1b_king_diamonds, \
        strip_1b_ace_spades, \
        strip_1b_two_spades, \
        strip_1b_three_spades, \
        strip_1b_four_spades, \
        strip_1b_five_spades, \
        strip_1b_six_spades, \
        strip_1b_seven_spades, \
        strip_1b_eight_spades, \
        strip_1b_nine_spades, \
        strip_1b_ten_spades, \
        strip_1b_jack_spades, \
        strip_1b_queen_spades, \
        strip_1b_king_spades, \
        strip_1b_ace_clubs, \
        strip_1b_two_clubs, \
        strip_1b_three_clubs, \
        strip_1b_four_clubs, \
        strip_1b_five_clubs, \
        strip_1b_six_clubs, \
        strip_1b_seven_clubs, \
        strip_1b_eight_clubs, \
        strip_1b_nine_clubs, \
        strip_1b_ten_clubs, \
        strip_1b_jack_clubs, \
        strip_1b_queen_clubs, \
        strip_1b_king_clubs, \
        strip_1b_joker
strip_1b_pointers_l: .lobytes strip_1b_pointers
strip_1b_pointers_h: .hibytes strip_1b_pointers
strip_1_ace_hearts: .byte $00, $10, $2C, $3C, $2A, $48
strip_2_ace_hearts: .byte $01, $11, $2D, $3D, $4A, $3B
strip_3_ace_hearts: .byte $3A, $4A, $8C, $9C, $00, $10
strip_4_ace_hearts: .byte $4B, $2B, $8D, $9D, $01, $11
strip_1b_ace_hearts: .byte $40, $10, $2C, $3C, $2A, $49
strip_1_two_hearts: .byte $02, $12, $2C, $3C, $2A, $48
strip_2_two_hearts: .byte $03, $13, $2D, $3D, $4A, $3B
strip_3_two_hearts: .byte $3A, $4A, $8C, $9C, $02, $12
strip_4_two_hearts: .byte $4B, $2B, $8D, $9D, $03, $13
strip_1b_two_hearts: .byte $41, $12, $2C, $3C, $2A, $49
strip_1_three_hearts: .byte $04, $14, $2C, $3C, $2A, $48
strip_2_three_hearts: .byte $05, $15, $2D, $3D, $4A, $3B
strip_3_three_hearts: .byte $3A, $4A, $8C, $9C, $04, $14
strip_4_three_hearts: .byte $4B, $2B, $8D, $9D, $05, $15
strip_1b_three_hearts: .byte $42, $14, $2C, $3C, $2A, $49
strip_1_four_hearts: .byte $06, $16, $2C, $3C, $2A, $48
strip_2_four_hearts: .byte $07, $17, $2D, $3D, $4A, $3B
strip_3_four_hearts: .byte $3A, $4A, $8C, $9C, $06, $16
strip_4_four_hearts: .byte $4B, $2B, $8D, $9D, $07, $17
strip_1b_four_hearts: .byte $43, $16, $2C, $3C, $2A, $49
strip_1_five_hearts: .byte $08, $18, $2C, $3C, $2A, $48
strip_2_five_hearts: .byte $09, $19, $2D, $3D, $4A, $3B
strip_3_five_hearts: .byte $3A, $4A, $8C, $9C, $08, $18
strip_4_five_hearts: .byte $4B, $2B, $8D, $9D, $09, $19
strip_1b_five_hearts: .byte $44, $18, $2C, $3C, $2A, $49
strip_1_six_hearts: .byte $0A, $1A, $2C, $3C, $2A, $48
strip_2_six_hearts: .byte $0B, $1B, $2D, $3D, $4A, $3B
strip_3_six_hearts: .byte $3A, $4A, $8C, $9C, $0A, $1A
strip_4_six_hearts: .byte $4B, $2B, $8D, $9D, $0B, $1B
strip_1b_six_hearts: .byte $45, $1A, $2C, $3C, $2A, $49
strip_1_seven_hearts: .byte $0C, $1C, $2C, $3C, $2A, $48
strip_2_seven_hearts: .byte $0D, $1D, $2D, $3D, $4A, $3B
strip_3_seven_hearts: .byte $3A, $4A, $8C, $9C, $0C, $1C
strip_4_seven_hearts: .byte $4B, $2B, $8D, $9D, $0D, $1D
strip_1b_seven_hearts: .byte $46, $1C, $2C, $3C, $2A, $49
strip_1_eight_hearts: .byte $0E, $1E, $2C, $3C, $2A, $48
strip_2_eight_hearts: .byte $0F, $1F, $2D, $3D, $4A, $3B
strip_3_eight_hearts: .byte $3A, $4A, $8C, $9C, $0E, $1E
strip_4_eight_hearts: .byte $4B, $2B, $8D, $9D, $0F, $1F
strip_1b_eight_hearts: .byte $47, $1E, $2C, $3C, $2A, $49
strip_1_nine_hearts: .byte $20, $30, $2C, $3C, $2A, $48
strip_2_nine_hearts: .byte $21, $31, $2D, $3D, $4A, $3B
strip_3_nine_hearts: .byte $3A, $4A, $8C, $9C, $20, $30
strip_4_nine_hearts: .byte $4B, $2B, $8D, $9D, $21, $31
strip_1b_nine_hearts: .byte $50, $30, $2C, $3C, $2A, $49
strip_1_ten_hearts: .byte $22, $32, $2C, $3C, $2A, $48
strip_2_ten_hearts: .byte $23, $33, $2D, $3D, $4A, $3B
strip_3_ten_hearts: .byte $3A, $4A, $8C, $9C, $22, $32
strip_4_ten_hearts: .byte $4B, $2B, $8D, $9D, $23, $33
strip_1b_ten_hearts: .byte $51, $32, $2C, $3C, $2A, $49
strip_1_jack_hearts: .byte $24, $34, $2C, $3C, $2A, $48
strip_2_jack_hearts: .byte $25, $35, $2D, $3D, $4A, $3B
strip_3_jack_hearts: .byte $3A, $4A, $8C, $9C, $24, $34
strip_4_jack_hearts: .byte $4B, $2B, $8D, $9D, $25, $35
strip_1b_jack_hearts: .byte $52, $34, $2C, $3C, $2A, $49
strip_1_queen_hearts: .byte $26, $36, $2C, $3C, $2A, $48
strip_2_queen_hearts: .byte $27, $37, $2D, $3D, $4A, $3B
strip_3_queen_hearts: .byte $3A, $4A, $8C, $9C, $26, $36
strip_4_queen_hearts: .byte $4B, $2B, $8D, $9D, $27, $37
strip_1b_queen_hearts: .byte $53, $36, $2C, $3C, $2A, $49
strip_1_king_hearts: .byte $28, $38, $2C, $3C, $2A, $48
strip_2_king_hearts: .byte $29, $39, $2D, $3D, $4A, $3B
strip_3_king_hearts: .byte $3A, $4A, $8C, $9C, $28, $38
strip_4_king_hearts: .byte $4B, $2B, $8D, $9D, $29, $39
strip_1b_king_hearts: .byte $54, $38, $2C, $3C, $2A, $49
strip_1_ace_diamonds: .byte $00, $10, $2E, $3E, $2A, $48
strip_2_ace_diamonds: .byte $01, $11, $2F, $3F, $4A, $3B
strip_3_ace_diamonds: .byte $3A, $4A, $8E, $9E, $00, $10
strip_4_ace_diamonds: .byte $4B, $2B, $8F, $9F, $01, $11
strip_1b_ace_diamonds: .byte $40, $10, $2E, $3E, $2A, $49
strip_1_two_diamonds: .byte $02, $12, $2E, $3E, $2A, $48
strip_2_two_diamonds: .byte $03, $13, $2F, $3F, $4A, $3B
strip_3_two_diamonds: .byte $3A, $4A, $8E, $9E, $02, $12
strip_4_two_diamonds: .byte $4B, $2B, $8F, $9F, $03, $13
strip_1b_two_diamonds: .byte $41, $12, $2E, $3E, $2A, $49
strip_1_three_diamonds: .byte $04, $14, $2E, $3E, $2A, $48
strip_2_three_diamonds: .byte $05, $15, $2F, $3F, $4A, $3B
strip_3_three_diamonds: .byte $3A, $4A, $8E, $9E, $04, $14
strip_4_three_diamonds: .byte $4B, $2B, $8F, $9F, $05, $15
strip_1b_three_diamonds: .byte $42, $14, $2E, $3E, $2A, $49
strip_1_four_diamonds: .byte $06, $16, $2E, $3E, $2A, $48
strip_2_four_diamonds: .byte $07, $17, $2F, $3F, $4A, $3B
strip_3_four_diamonds: .byte $3A, $4A, $8E, $9E, $06, $16
strip_4_four_diamonds: .byte $4B, $2B, $8F, $9F, $07, $17
strip_1b_four_diamonds: .byte $43, $16, $2E, $3E, $2A, $49
strip_1_five_diamonds: .byte $08, $18, $2E, $3E, $2A, $48
strip_2_five_diamonds: .byte $09, $19, $2F, $3F, $4A, $3B
strip_3_five_diamonds: .byte $3A, $4A, $8E, $9E, $08, $18
strip_4_five_diamonds: .byte $4B, $2B, $8F, $9F, $09, $19
strip_1b_five_diamonds: .byte $44, $18, $2E, $3E, $2A, $49
strip_1_six_diamonds: .byte $0A, $1A, $2E, $3E, $2A, $48
strip_2_six_diamonds: .byte $0B, $1B, $2F, $3F, $4A, $3B
strip_3_six_diamonds: .byte $3A, $4A, $8E, $9E, $0A, $1A
strip_4_six_diamonds: .byte $4B, $2B, $8F, $9F, $0B, $1B
strip_1b_six_diamonds: .byte $45, $1A, $2E, $3E, $2A, $49
strip_1_seven_diamonds: .byte $0C, $1C, $2E, $3E, $2A, $48
strip_2_seven_diamonds: .byte $0D, $1D, $2F, $3F, $4A, $3B
strip_3_seven_diamonds: .byte $3A, $4A, $8E, $9E, $0C, $1C
strip_4_seven_diamonds: .byte $4B, $2B, $8F, $9F, $0D, $1D
strip_1b_seven_diamonds: .byte $46, $1C, $2E, $3E, $2A, $49
strip_1_eight_diamonds: .byte $0E, $1E, $2E, $3E, $2A, $48
strip_2_eight_diamonds: .byte $0F, $1F, $2F, $3F, $4A, $3B
strip_3_eight_diamonds: .byte $3A, $4A, $8E, $9E, $0E, $1E
strip_4_eight_diamonds: .byte $4B, $2B, $8F, $9F, $0F, $1F
strip_1b_eight_diamonds: .byte $47, $1E, $2E, $3E, $2A, $49
strip_1_nine_diamonds: .byte $20, $30, $2E, $3E, $2A, $48
strip_2_nine_diamonds: .byte $21, $31, $2F, $3F, $4A, $3B
strip_3_nine_diamonds: .byte $3A, $4A, $8E, $9E, $20, $30
strip_4_nine_diamonds: .byte $4B, $2B, $8F, $9F, $21, $31
strip_1b_nine_diamonds: .byte $50, $30, $2E, $3E, $2A, $49
strip_1_ten_diamonds: .byte $22, $32, $2E, $3E, $2A, $48
strip_2_ten_diamonds: .byte $23, $33, $2F, $3F, $4A, $3B
strip_3_ten_diamonds: .byte $3A, $4A, $8E, $9E, $22, $32
strip_4_ten_diamonds: .byte $4B, $2B, $8F, $9F, $23, $33
strip_1b_ten_diamonds: .byte $51, $32, $2E, $3E, $2A, $49
strip_1_jack_diamonds: .byte $24, $34, $2E, $3E, $2A, $48
strip_2_jack_diamonds: .byte $25, $35, $2F, $3F, $4A, $3B
strip_3_jack_diamonds: .byte $3A, $4A, $8E, $9E, $24, $34
strip_4_jack_diamonds: .byte $4B, $2B, $8F, $9F, $25, $35
strip_1b_jack_diamonds: .byte $52, $34, $2E, $3E, $2A, $49
strip_1_queen_diamonds: .byte $26, $36, $2E, $3E, $2A, $48
strip_2_queen_diamonds: .byte $27, $37, $2F, $3F, $4A, $3B
strip_3_queen_diamonds: .byte $3A, $4A, $8E, $9E, $26, $36
strip_4_queen_diamonds: .byte $4B, $2B, $8F, $9F, $27, $37
strip_1b_queen_diamonds: .byte $53, $36, $2E, $3E, $2A, $49
strip_1_king_diamonds: .byte $28, $38, $2E, $3E, $2A, $48
strip_2_king_diamonds: .byte $29, $39, $2F, $3F, $4A, $3B
strip_3_king_diamonds: .byte $3A, $4A, $8E, $9E, $28, $38
strip_4_king_diamonds: .byte $4B, $2B, $8F, $9F, $29, $39
strip_1b_king_diamonds: .byte $54, $38, $2E, $3E, $2A, $49
strip_1_ace_spades: .byte $00, $10, $4C, $5C, $2A, $48
strip_2_ace_spades: .byte $01, $11, $4D, $5D, $4A, $3B
strip_3_ace_spades: .byte $3A, $4A, $AC, $BC, $00, $10
strip_4_ace_spades: .byte $4B, $2B, $AD, $BD, $01, $11
strip_1b_ace_spades: .byte $40, $10, $4C, $5C, $2A, $49
strip_1_two_spades: .byte $02, $12, $4C, $5C, $2A, $48
strip_2_two_spades: .byte $03, $13, $4D, $5D, $4A, $3B
strip_3_two_spades: .byte $3A, $4A, $AC, $BC, $02, $12
strip_4_two_spades: .byte $4B, $2B, $AD, $BD, $03, $13
strip_1b_two_spades: .byte $41, $12, $4C, $5C, $2A, $49
strip_1_three_spades: .byte $04, $14, $4C, $5C, $2A, $48
strip_2_three_spades: .byte $05, $15, $4D, $5D, $4A, $3B
strip_3_three_spades: .byte $3A, $4A, $AC, $BC, $04, $14
strip_4_three_spades: .byte $4B, $2B, $AD, $BD, $05, $15
strip_1b_three_spades: .byte $42, $14, $4C, $5C, $2A, $49
strip_1_four_spades: .byte $06, $16, $4C, $5C, $2A, $48
strip_2_four_spades: .byte $07, $17, $4D, $5D, $4A, $3B
strip_3_four_spades: .byte $3A, $4A, $AC, $BC, $06, $16
strip_4_four_spades: .byte $4B, $2B, $AD, $BD, $07, $17
strip_1b_four_spades: .byte $43, $16, $4C, $5C, $2A, $49
strip_1_five_spades: .byte $08, $18, $4C, $5C, $2A, $48
strip_2_five_spades: .byte $09, $19, $4D, $5D, $4A, $3B
strip_3_five_spades: .byte $3A, $4A, $AC, $BC, $08, $18
strip_4_five_spades: .byte $4B, $2B, $AD, $BD, $09, $19
strip_1b_five_spades: .byte $44, $18, $4C, $5C, $2A, $49
strip_1_six_spades: .byte $0A, $1A, $4C, $5C, $2A, $48
strip_2_six_spades: .byte $0B, $1B, $4D, $5D, $4A, $3B
strip_3_six_spades: .byte $3A, $4A, $AC, $BC, $0A, $1A
strip_4_six_spades: .byte $4B, $2B, $AD, $BD, $0B, $1B
strip_1b_six_spades: .byte $45, $1A, $4C, $5C, $2A, $49
strip_1_seven_spades: .byte $0C, $1C, $4C, $5C, $2A, $48
strip_2_seven_spades: .byte $0D, $1D, $4D, $5D, $4A, $3B
strip_3_seven_spades: .byte $3A, $4A, $AC, $BC, $0C, $1C
strip_4_seven_spades: .byte $4B, $2B, $AD, $BD, $0D, $1D
strip_1b_seven_spades: .byte $46, $1C, $4C, $5C, $2A, $49
strip_1_eight_spades: .byte $0E, $1E, $4C, $5C, $2A, $48
strip_2_eight_spades: .byte $0F, $1F, $4D, $5D, $4A, $3B
strip_3_eight_spades: .byte $3A, $4A, $AC, $BC, $0E, $1E
strip_4_eight_spades: .byte $4B, $2B, $AD, $BD, $0F, $1F
strip_1b_eight_spades: .byte $47, $1E, $4C, $5C, $2A, $49
strip_1_nine_spades: .byte $20, $30, $4C, $5C, $2A, $48
strip_2_nine_spades: .byte $21, $31, $4D, $5D, $4A, $3B
strip_3_nine_spades: .byte $3A, $4A, $AC, $BC, $20, $30
strip_4_nine_spades: .byte $4B, $2B, $AD, $BD, $21, $31
strip_1b_nine_spades: .byte $50, $30, $4C, $5C, $2A, $49
strip_1_ten_spades: .byte $22, $32, $4C, $5C, $2A, $48
strip_2_ten_spades: .byte $23, $33, $4D, $5D, $4A, $3B
strip_3_ten_spades: .byte $3A, $4A, $AC, $BC, $22, $32
strip_4_ten_spades: .byte $4B, $2B, $AD, $BD, $23, $33
strip_1b_ten_spades: .byte $51, $32, $4C, $5C, $2A, $49
strip_1_jack_spades: .byte $24, $34, $4C, $5C, $2A, $48
strip_2_jack_spades: .byte $25, $35, $4D, $5D, $4A, $3B
strip_3_jack_spades: .byte $3A, $4A, $AC, $BC, $24, $34
strip_4_jack_spades: .byte $4B, $2B, $AD, $BD, $25, $35
strip_1b_jack_spades: .byte $52, $34, $4C, $5C, $2A, $49
strip_1_queen_spades: .byte $26, $36, $4C, $5C, $2A, $48
strip_2_queen_spades: .byte $27, $37, $4D, $5D, $4A, $3B
strip_3_queen_spades: .byte $3A, $4A, $AC, $BC, $26, $36
strip_4_queen_spades: .byte $4B, $2B, $AD, $BD, $27, $37
strip_1b_queen_spades: .byte $53, $36, $4C, $5C, $2A, $49
strip_1_king_spades: .byte $28, $38, $4C, $5C, $2A, $48
strip_2_king_spades: .byte $29, $39, $4D, $5D, $4A, $3B
strip_3_king_spades: .byte $3A, $4A, $AC, $BC, $28, $38
strip_4_king_spades: .byte $4B, $2B, $AD, $BD, $29, $39
strip_1b_king_spades: .byte $54, $38, $4C, $5C, $2A, $49
strip_1_ace_clubs: .byte $00, $10, $4E, $5E, $2A, $48
strip_2_ace_clubs: .byte $01, $11, $4F, $5F, $4A, $3B
strip_3_ace_clubs: .byte $3A, $4A, $AE, $BE, $00, $10
strip_4_ace_clubs: .byte $4B, $2B, $AF, $BF, $01, $11
strip_1b_ace_clubs: .byte $40, $10, $4E, $5E, $2A, $49
strip_1_two_clubs: .byte $02, $12, $4E, $5E, $2A, $48
strip_2_two_clubs: .byte $03, $13, $4F, $5F, $4A, $3B
strip_3_two_clubs: .byte $3A, $4A, $AE, $BE, $02, $12
strip_4_two_clubs: .byte $4B, $2B, $AF, $BF, $03, $13
strip_1b_two_clubs: .byte $41, $12, $4E, $5E, $2A, $49
strip_1_three_clubs: .byte $04, $14, $4E, $5E, $2A, $48
strip_2_three_clubs: .byte $05, $15, $4F, $5F, $4A, $3B
strip_3_three_clubs: .byte $3A, $4A, $AE, $BE, $04, $14
strip_4_three_clubs: .byte $4B, $2B, $AF, $BF, $05, $15
strip_1b_three_clubs: .byte $42, $14, $4E, $5E, $2A, $49
strip_1_four_clubs: .byte $06, $16, $4E, $5E, $2A, $48
strip_2_four_clubs: .byte $07, $17, $4F, $5F, $4A, $3B
strip_3_four_clubs: .byte $3A, $4A, $AE, $BE, $06, $16
strip_4_four_clubs: .byte $4B, $2B, $AF, $BF, $07, $17
strip_1b_four_clubs: .byte $43, $16, $4E, $5E, $2A, $49
strip_1_five_clubs: .byte $08, $18, $4E, $5E, $2A, $48
strip_2_five_clubs: .byte $09, $19, $4F, $5F, $4A, $3B
strip_3_five_clubs: .byte $3A, $4A, $AE, $BE, $08, $18
strip_4_five_clubs: .byte $4B, $2B, $AF, $BF, $09, $19
strip_1b_five_clubs: .byte $44, $18, $4E, $5E, $2A, $49
strip_1_six_clubs: .byte $0A, $1A, $4E, $5E, $2A, $48
strip_2_six_clubs: .byte $0B, $1B, $4F, $5F, $4A, $3B
strip_3_six_clubs: .byte $3A, $4A, $AE, $BE, $0A, $1A
strip_4_six_clubs: .byte $4B, $2B, $AF, $BF, $0B, $1B
strip_1b_six_clubs: .byte $45, $1A, $4E, $5E, $2A, $49
strip_1_seven_clubs: .byte $0C, $1C, $4E, $5E, $2A, $48
strip_2_seven_clubs: .byte $0D, $1D, $4F, $5F, $4A, $3B
strip_3_seven_clubs: .byte $3A, $4A, $AE, $BE, $0C, $1C
strip_4_seven_clubs: .byte $4B, $2B, $AF, $BF, $0D, $1D
strip_1b_seven_clubs: .byte $46, $1C, $4E, $5E, $2A, $49
strip_1_eight_clubs: .byte $0E, $1E, $4E, $5E, $2A, $48
strip_2_eight_clubs: .byte $0F, $1F, $4F, $5F, $4A, $3B
strip_3_eight_clubs: .byte $3A, $4A, $AE, $BE, $0E, $1E
strip_4_eight_clubs: .byte $4B, $2B, $AF, $BF, $0F, $1F
strip_1b_eight_clubs: .byte $47, $1E, $4E, $5E, $2A, $49
strip_1_nine_clubs: .byte $20, $30, $4E, $5E, $2A, $48
strip_2_nine_clubs: .byte $21, $31, $4F, $5F, $4A, $3B
strip_3_nine_clubs: .byte $3A, $4A, $AE, $BE, $20, $30
strip_4_nine_clubs: .byte $4B, $2B, $AF, $BF, $21, $31
strip_1b_nine_clubs: .byte $50, $30, $4E, $5E, $2A, $49
strip_1_ten_clubs: .byte $22, $32, $4E, $5E, $2A, $48
strip_2_ten_clubs: .byte $23, $33, $4F, $5F, $4A, $3B
strip_3_ten_clubs: .byte $3A, $4A, $AE, $BE, $22, $32
strip_4_ten_clubs: .byte $4B, $2B, $AF, $BF, $23, $33
strip_1b_ten_clubs: .byte $51, $32, $4E, $5E, $2A, $49
strip_1_jack_clubs: .byte $24, $34, $4E, $5E, $2A, $48
strip_2_jack_clubs: .byte $25, $35, $4F, $5F, $4A, $3B
strip_3_jack_clubs: .byte $3A, $4A, $AE, $BE, $24, $34
strip_4_jack_clubs: .byte $4B, $2B, $AF, $BF, $25, $35
strip_1b_jack_clubs: .byte $52, $34, $4E, $5E, $2A, $49
strip_1_queen_clubs: .byte $26, $36, $4E, $5E, $2A, $48
strip_2_queen_clubs: .byte $27, $37, $4F, $5F, $4A, $3B
strip_3_queen_clubs: .byte $3A, $4A, $AE, $BE, $26, $36
strip_4_queen_clubs: .byte $4B, $2B, $AF, $BF, $27, $37
strip_1b_queen_clubs: .byte $53, $36, $4E, $5E, $2A, $49
strip_1_king_clubs: .byte $28, $38, $4E, $5E, $2A, $48
strip_2_king_clubs: .byte $29, $39, $4F, $5F, $4A, $3B
strip_3_king_clubs: .byte $3A, $4A, $AE, $BE, $28, $38
strip_4_king_clubs: .byte $4B, $2B, $AF, $BF, $29, $39
strip_1b_king_clubs: .byte $54, $38, $4E, $5E, $2A, $49
strip_1_joker: .byte $56, $2A, $2A, $2A, $2A, $48
strip_2_joker: .byte $3A, $8A, $9A, $AA, $BA, $3B
strip_3_joker: .byte $3A, $8B, $9B, $AB, $BB, $3B
strip_4_joker: .byte $4B, $2B, $2B, $2B, $2B, $57
strip_1b_joker: .byte $55, $2A, $2A, $2A, $2A, $49
